name: jest-ReactJs
run-name: ${{github.actor}} is learning using jest to test ReactJs
on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checks out your repository onto the runner. You should use the checkout anytime your workflow will use the repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jest-reactjs

      - name: Install modules
        run: npm install
      - name: Testing before building
        run: npm test
      - name: Build
        run: npm run build

      - name: Set up pages
        uses: actions/configure-pages@v3
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
      - name: Deploy to Github pages
        uses: actions/deploy-pages@v1
      - name: Deploy React App
        id: deployment
        uses: actions/deploy-pages@v1
